spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useSSL=false&characterEncoding=UTF-8&serverTimeZone=UTC
    username: moapp
    password: mo1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql : true
    hibernate:
      ddl-auto: update

# local 환경
---
server:
  address: localhost
  port: 8080
  error:
    include-stacktrace: never
spring:
  config:
    activate:
      on-profile: local
